### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by ghost** [cmbaxter/mastering-akka#12]
Hello,

Not sure if this is the right place for this comment / question, but here it goes...

I'm attempting to follow along the Mastering Akka book.  I'm able to get the project running just fine via the docker commands.  I can hit the REST endpoints as described in the beginning chapter.

I am however struggling to get an error-free PROJECT setup.  When opening 'initial-example-app' using IntelliJ IDEA, and configuring the project, I notice there are a number of missing dependencies.

Based on my limited prior knowledge of SBT, all of the dependencies for the project _should_ be automatically downloaded.  That does not appear to be happening, however.  Here's a list of **some** of the missing dependencies:

**Server.scala**
_MISSING_ com.packt.masteringakka.bookstore.common.PostgresDb
_MISSING_ com.packt.masteringakka.bookstore.common.Bootstrap

**SalesOrderManager.scala**
_MISSING_ slick.dbio.DBIOAction
_MISSING_ slick.jdbc.SQLActionBuilder
_MISSING_ slick.jdbc.GetResult
_MISSING_ akka.util.Timeout
_MISSING_ com.packt.masteringakka.bookstore.domain.credit.CreditCardTransaction

And there are many more.

I'd love to get the project setup and configured correctly, so that I can read the code.  But with it currently missing dependencies, it's a sea of red.  I don't see anything in the book about how to configure the project within an IDE.  What am I doing wrong?

**Comment by cmbaxter** [comment]
Hey @ermterm, I didn't want to push anyone into having to use an IDE in the book, as that can be a pretty divisive matter, whether to IDE or not and also if you do, whether to use IntelliJ or Eclipse.  For what it's worth though, I use Eclipse while developing all of the code for the book, so it definitely can work when using an IDE.

Initially, the code for the example app is setup as an SBT Multi Project Build.  In fact, there is a diagram on page 9 that details the different projects that make up the multi project build and how they depend on each other.  Every of the service projects project depends on `common` and then the `server` project depends on all of those service projects (and transitively `common`).  When you initiate a build of the entire set of projects via SBT, it will first build `common` and then the service projects and lastly, `server` as that's how the SBT build.sbt file at the root describes the project relationships.

So in looking at your issues, `Server.scala` seems to be upset because it can't find the code from the common project.  Also, `SalesOrderManager` is upset for the same reason, and also because it did not pull in the transitive dependencies from common for Akka and Slick.  

There is an Eclipse plugin that allows one to generate all of the eclipse artifacts (`.classpath` and `.project` files) that will connect all of the projects together together in such a way that all of the dependencies are properly setup.  I know there is something similar for IntelliJ.  You may want to start with something like this:

https://www.jetbrains.com/help/idea/2016.2/getting-started-with-sbt.html

Or you can also download the Scala Eclipse IDE and then the sbteclipse and go from there.  I hope this all helps.  Good luck getting things setup.

**Comment by ghost** [comment]
Hi @cmbaxter thanks for the quick reply!

I feel stupid!  I had imported the project manually, and tried to configure each module individually as an sbt module.  The solution was in the link you provided, to import the project from existing sources as a top level SBT project.

Thanks!
